services:
  redis:
    image: redis/redis-stack:latest
    hostname: redis
    restart: always
    ports:
      - '6379:6379'
      - '8001:8001'
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG" ]
      interval: 1s
      timeout: 3s
      retries: 5
  app:
    image: edoatley/boot-ai:latest
    # Keep secrets in .env  
    env_file:
      - .env
    environment:
      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PORT: 6379
    ports:
      - '8080:8080'
    depends_on:
      - redis
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080/actuator/health || exit 1"]
      interval: 1s
      timeout: 3s
      retries: 5
